global:
  name: train-abinet
  phase: train
  stage: train-super
  workdir: workdir
  seed: ~
 
dataset:
  root: 'data/ICDAR2013+2015/train_data'
  train: {
    labels: 'data/ICDAR2013+2015/train.txt',
    roots: ['data/training/MJ/MJ_train/', 
            'data/training/MJ/MJ_test/', 
            'data/training/MJ/MJ_valid/', 
            'data/training/ST'],
    batch_size: 8
  }
  test: {
    labels: 'data/ICDAR2013+2015/test.txt',
    roots: ['data/evaluation/IIIT5k_3000', 
            'data/evaluation/SVT', 
            'data/evaluation/SVTP',
            'data/evaluation/IC13_857',
            'data/evaluation/IC15_1811',
            'data/evaluation/CUTE80'],
    batch_size: 384
  }
  multiscales: False
  num_workers: 14

training:
  epochs: 10
  show_iters: 50
  eval_iters: 3000
  save_iters: 3000

optimizer:
  type: Adam
  true_wd: False
  wd: 0.0
  bn_wd: False
  clip_grad: 20
  lr: 0.0001
  args: {
    betas: !!python/tuple [0.9, 0.999], # for default Adam 
  }
  scheduler: {
    periods: [6, 4],
    gamma: 0.1,
  }

model:
  # checkpoint: checkpoints/best-pretrain-vision-model.pth
  loss_weight: 1
  attention: 'position'
  backbone: 'transformer'
  backbone_ln: 3
